[controlplane]
master_node ansible_host=<master_public_ip> ansible_user=ubuntu

[workers]
worker1 ansible_host=<worker1_public_ip> ansible_user=ubuntu
worker2 ansible_host=<worker2_public_ip> ansible_user=ubuntu

[k8s:children]
controlplane
workers
