- name: Run common setup on all nodes
  hosts: controlplane workers
  become: yes
  roles:
    - role: kubeadm
      tasks_from: configure_common.yaml

- name: Configure master node
  hosts: controlplane
  become: yes
  roles:
    - role: kubeadm
      tasks_from: configure_master.yaml
