- name: Run common setup on all nodes
  hosts: all
  become: yes
  tasks:
    - include_role:
        name: kubeadm
        tasks_from: configure_common.yaml

- name: Configure master node
  hosts: controlplane
  become: yes
  tasks:
    - include_role:
        name: kubeadm
        tasks_from: configure_master.yaml
