- name: Run common setup on all nodes
  hosts: all
  become: yes
  become_user: ubuntu
  tasks:
    - include_role:
        name: kubeadm
        tasks_from: configure_common.yaml

- name: Configure master node
  hosts: controlplane
  become: yes
  become_user: ubuntu
  tasks:
    - include_role:
        name: kubeadm
        tasks_from: configure_master.yaml

- name: Join worker nodes to the cluster
  hosts: workers
  become: yes
  become_user: ubuntu
  tasks:
    - include_role:
        name: kubeadm
        tasks_from: join_workers.yaml
        
  


