- name: Copy common.sh script to the remote node
  copy:
    src: "{{ role_path }}/files/common.sh"
    dest: /tmp/common.sh
    mode: '0755'

- name: Run common.sh script on all nodes
  shell: /tmp/common.sh
  become: yes
