- name: Copy master.sh script to the master node
  copy:
    src: "{{ role_path }}/files/master.sh"
    dest: /tmp/master.sh
    mode: '0755'

- name: Run master.sh script on the master node
  shell: /tmp/master.sh
  args:
    creates: /etc/kubernetes/admin.conf
  become: yes

- name: Retrieve kubeadm join command
  shell: kubeadm token create --print-join-command
  register: join_command
  become: yes

- name: Save join command to a file
  copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/join_command.sh
  become: yes
